### ISSUE TITLE
Issue with typings on sub-paths with traditional (non Deno) TS projects

### ISSUE THREAD

**Issue by josepot** [paritytech/capi#1106]
## Bug Report

TS is unable to find the type declarations of (at least) the `capi/nets` module

### [DEMO](https://stackblitz.com/edit/stackblitz-starters-hf6lss?file=package.json,src%2Fmain.ts)

**Comment by tjjfvi** [comment]
I've merged your PR as it deduplicates our type declarations, but the issue here is that you need `"moduleResolution": "Node16"` (or `NodeNext`), as we use subpath exports.

**Comment by josepot** [comment]
I'm re-opening it b/c I'm quite certain that the issue still persists.

**Comment by tjjfvi** [comment]
You need to edit your `tsconfig.json` to set `moduleResolution` to `Node16`. This fixes the type error.

**Comment by josepot** [comment]
> You need to edit your `tsconfig.json` to set `moduleResolution` to `Node16`. This fixes the type error.

Indeed. It does. Thanks!

**Comment by josepot** [comment]
BTW you may find [this](https://github.com/smol-dot/smoldot/issues/787#issuecomment-1606157019) (and/or [this](https://github.com/smol-dot/smoldot/pull/820)) interesting :wink: . cc @harrysolovay
